# Generated by Django 5.2.6 on 2025-09-26 14:17

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image supplémentaire pour le projet', upload_to='projets/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.models.validate_file_size])),
                ('legende', models.CharField(blank=True, help_text="Légende optionnelle pour l'image", max_length=200, null=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (plus petit = premier)")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.projet')),
            ],
            options={
                'verbose_name': 'Image de projet',
                'verbose_name_plural': 'Images de projet',
                'ordering': ['ordre', 'date_creation'],
            },
        ),
    ]
