# Generated by Django 5.2.6 on 2025-09-14 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='association',
            field=models.ForeignKey(blank=True, help_text='Association porteuse du projet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='core.association'),
        ),
    ]
