# Generated by Django 5.2.6 on 2025-09-24 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionadmin',
            name='initiateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_initiées', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionadmin',
            name='palier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.palier'),
        ),
        migrations.AlterField(
            model_name='transactionadmin',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_reçues', to=settings.AUTH_USER_MODEL),
        ),
    ]
