# Generated by Django 5.2.6 on 2025-10-20 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='association',
            field=models.ForeignKey(blank=True, help_text='Association destinataire pour les transferts directs', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.association'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('validate', 'Validation'), ('reject', 'Rejet'), ('verify', 'Vérification'), ('refund', 'Remboursement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='statut',
            field=models.CharField(choices=[('SUCCESS', 'Succès'), ('FAILURE', 'Échec')], default='SUCCESS', max_length=50),
        ),
        migrations.AlterField(
            model_name='fichierpreuve',
            name='type_fichier',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo'), ('document', 'Document'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='preuvepalier',
            name='statut',
            field=models.CharField(choices=[('non_soumis', 'Not submitted'), ('en_attente', 'Pending verification'), ('approuve', 'Approved'), ('rejete', 'Rejected'), ('modif', 'Modification required')], default='non_soumis', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='contributeur',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['porteur', 'donateur', 'investisseur', 'association']}, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='contributeur_anonymise',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.CharField(choices=[('operator', 'Vers opérateur'), ('project', 'Vers projet direct'), ('beneficiary', 'Vers bénéficiaire'), ('association', 'Vers association direct')], default='operator', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hedera_transaction_hash',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projet'),
        ),
    ]
