# Generated by Django 5.2.6 on 2025-09-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Image de couverture du projet (recommandé: 1200x600px)', null=True, upload_to='covers/projets/'),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Date de fin de la campagne de financement', null=True),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['date_fin'], name='core_projet_date_fi_5423e2_idx'),
        ),
    ]
