# Generated by Django 5.2.6 on 2025-09-12 04:56

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='categorie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='projet',
            name='tags',
        ),
        migrations.RenameIndex(
            model_name='projet',
            new_name='core_projet_categor_81a315_idx',
            old_name='core_projet_categor_b4078c_idx',
        ),
        migrations.AddField(
            model_name='projet',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='niveaufinancement',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='projet',
            name='budget_detaille',
            field=models.FileField(blank=True, null=True, upload_to='documents/projets/', validators=[core.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='projet',
            name='document_justificatif',
            field=models.FileField(blank=True, null=True, upload_to='documents/projets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png']), core.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='projet',
            name='plan_financement',
            field=models.FileField(blank=True, null=True, upload_to='documents/projets/', validators=[core.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('actif', 'Actif - Campagne en cours'), ('suspendu', 'Suspendu temporairement'), ('termine', 'Terminé avec succès'), ('echec', 'Échec de la campagne'), ('annule', 'Annulé'), ('rejete', 'Rejeté')], default='brouillon', max_length=20),
        ),
        migrations.DeleteModel(
            name='CategorieProjet',
        ),
        migrations.DeleteModel(
            name='TagProjet',
        ),
        migrations.AddField(
            model_name='projet',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
