# Generated by Django 5.2.6 on 2025-09-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palier',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée de l’utilisation des fonds pour ce palier'),
        ),
        migrations.AddField(
            model_name='palier',
            name='titre',
            field=models.CharField(default='test', help_text='Titre court du palier (ex: Achat terrain)', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='palier',
            name='pourcentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
