# Generated by Django 5.2.6 on 2025-09-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imageprojet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hedera_message_id',
            field=models.CharField(blank=True, help_text='ID du message HCS Hedera', max_length=150, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['hedera_message_id'], name='core_transa_hedera__2292a5_idx'),
        ),
    ]
