# Generated by Django 5.2.6 on 2025-09-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_projet_categorie_remove_projet_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetimage',
            name='projet',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='gallery_images',
        ),
        migrations.AddField(
            model_name='projet',
            name='niveaux_financement_json',
            field=models.JSONField(blank=True, help_text='Structure JSON pour stocker les niveaux de financement et récompenses', null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('actif', 'Actif - Campagne en cours'), ('suspendu', 'Suspendu temporairement'), ('termine', 'Terminé avec succès'), ('echec', 'Échec de la campagne'), ('annule', 'Annulé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
        migrations.DeleteModel(
            name='NiveauFinancement',
        ),
        migrations.DeleteModel(
            name='ProjetImage',
        ),
    ]
