# Generated by Django 5.2.6 on 2025-09-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transactionadmin_initiateur_transactionadmin_palier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionadmin',
            name='hedera_message_hashscan_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionadmin',
            name='hedera_message_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
