# Generated by Django 5.2.6 on 2025-09-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_projetimage_projet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='autre_categorie',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre catégorie (si autre est sélectionné)'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='categorie',
            field=models.CharField(choices=[('agriculture', 'Agriculture et Agroalimentaire'), ('artisanat', 'Artisanat et Métiers'), ('commerce', 'Commerce et Vente'), ('education', 'Éducation et Formation'), ('sante', 'Santé et Bien-être'), ('technologie', 'Technologie et Innovation'), ('energie', 'Énergie et Environnement'), ('tourisme', 'Tourisme et Hôtellerie'), ('culture', 'Culture et Arts'), ('social', 'Social et Communautaire'), ('sport', 'Sport et Loisirs'), ('immobilier', 'Immobilier et Construction'), ('transport', 'Transport et Mobilité'), ('finance', 'Finance et Microcrédit'), ('autre', 'Autre domaine')], default='commerce', max_length=200, verbose_name='Catégorie du projet'),
        ),
    ]
