# Generated by Django 5.2.6 on 2025-09-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transactionadmin_hedera_message_hashscan_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='hedera_message_id',
        ),
        migrations.AlterField(
            model_name='projet',
            name='categorie',
            field=models.CharField(choices=[('agriculture', 'Agriculture & Agribusiness'), ('artisanat', 'Crafts & Trades'), ('commerce', 'Commerce & Sales'), ('education', 'Education & Training'), ('sante', 'Health & Wellness'), ('technologie', 'Technology & Innovation'), ('energie', 'Energy & Environment'), ('tourisme', 'Tourism & Hospitality'), ('culture', 'Culture & Arts'), ('social', 'Social & Community'), ('sport', 'Sports & Leisure'), ('immobilier', 'Real Estate & Construction'), ('transport', 'Transport & Mobility'), ('finance', 'Finance & Microcredit'), ('autre', 'Other')], default='commerce', max_length=200, verbose_name='Catégorie du projet'),
        ),
    ]
