# Generated by Django 5.2.6 on 2025-09-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction_hedera_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
