# Generated by Django 5.2.6 on 2025-09-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='actions_en_cours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='date_agrement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='date_creation_association',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='description_longue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='nombre_adherents',
            field=models.IntegerField(blank=True, help_text='Nombre approximatif d’adhérents', null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='numero_agrement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='partenariats',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='statut_juridique',
            field=models.CharField(choices=[('association', 'Association'), ('ong', 'ONG'), ('fondation', 'Fondation'), ('autre', 'Autre statut')], default='association', max_length=50),
        ),
    ]
