# Generated by Django 5.2.6 on 2025-09-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transactionadmin_hedera_message_hashscan_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='hedera_message_id',
        ),
    ]
