# Generated by Django 5.2.6 on 2025-09-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_association_actions_en_cours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='verifiee',
        ),
        migrations.AddField(
            model_name='association',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mise en avant sur la plateforme'),
        ),
        migrations.AddField(
            model_name='association',
            name='valide',
            field=models.BooleanField(default=False, help_text="Profil validé par l'administration"),
        ),
    ]
