# Generated by Django 5.2.6 on 2025-09-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_transaction_hedera_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='type_financement',
            field=models.CharField(choices=[('don', 'Donations only'), ('pret', 'Loan with repayment'), ('equity', 'Equity investment'), ('recompense', 'Reward-based funding'), ('mixte', 'Mixed funding')], default='don', max_length=10),
        ),
    ]
