# Generated by Django 5.2.6 on 2025-09-12 20:46

import core.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projet_autre_categorie_alter_projet_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': [('can_audit', 'Peut effectuer des audits de transparence'), ('manage_users', 'Peut gérer tous les utilisateurs'), ('manage_projects', 'Peut gérer tous les projets'), ('manage_transactions', 'Peut gérer toutes les transactions'), ('view_dashboard', 'Peut voir le tableau de bord administrateur')]},
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Une brève description de vous-même', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_derniere_connexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(blank=True, help_text='Votre profil Facebook', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Autre'), ('non_specifie', 'Non spécifié')], default='non_specifie', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Votre profil LinkedIn', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(blank=True, help_text='Photo de profil (format carré recommandé, max 5 Mo)', null=True, upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), core.models.validate_profile_image_size]),
        ),
        migrations.AddField(
            model_name='user',
            name='site_web_perso',
            field=models.URLField(blank=True, help_text='Votre site web personnel', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, help_text='Votre profil Twitter', null=True),
        ),
    ]
