# Generated by Django 5.2.6 on 2025-09-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_association_verifiee_association_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='domaines_secondaires',
            field=models.CharField(blank=True, help_text='Domaines secondaires (séparés par des virgules)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='domaine_principal',
            field=models.CharField(choices=[('education', 'Éducation'), ('sante', 'Santé'), ('environnement', 'Environnement'), ('droits_humains', 'Droits humains'), ('developpement', 'Développement communautaire'), ('culture', 'Culture'), ('urgence', 'Aide humanitaire'), ('autre', 'Autre')], default='developpement', max_length=50),
        ),
    ]
