# Generated by Django 5.2.6 on 2025-09-12 22:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_options_user_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('slogan', models.CharField(blank=True, max_length=300, null=True)),
                ('description_courte', models.TextField(help_text='Description concise pour les listes', max_length=500)),
                ('description_longue', models.TextField(help_text="Description détaillée de l'association")),
                ('logo', models.ImageField(blank=True, help_text="Logo de l'association (format carré recommandé)", null=True, upload_to='associations/logos/')),
                ('cover_image', models.ImageField(blank=True, help_text='Image de couverture (format 1200x400px recommandé)', null=True, upload_to='associations/covers/')),
                ('domaine_principal', models.CharField(choices=[('environnement', 'Environnement & Écologie'), ('education', 'Éducation & Formation'), ('sante', 'Santé & Bien-être'), ('social', 'Action Sociale & Solidarité'), ('culture', 'Culture & Arts'), ('droits_humains', 'Droits Humains'), ('developpement', 'Développement International'), ('animaux', 'Protection Animale'), ('jeunesse', 'Jeunesse & Sports'), ('autre', 'Autre domaine')], max_length=50)),
                ('domaines_secondaires', models.CharField(blank=True, help_text='Domaines secondaires (séparés par des virgules)', max_length=200, null=True)),
                ('causes_defendues', models.TextField(help_text="Causes principales défendues par l'association")),
                ('statut_juridique', models.CharField(choices=[('loi_1901', 'Association Loi 1901'), ('fondation', 'Fondation'), ('ong', 'ONG Internationale'), ('cooperative', 'Coopérative'), ('autre', 'Autre statut')], max_length=20)),
                ('numero_rna', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro RNA')),
                ('date_creation', models.DateField()),
                ('date_publication_journal_officiel', models.DateField(blank=True, null=True)),
                ('adresse_siege', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(default='France', max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email_contact', models.EmailField(max_length=254)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('nombre_adherents', models.PositiveIntegerField(default=0)),
                ('nombre_beneficiaires', models.PositiveIntegerField(default=0)),
                ('budget_annuel', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pourcentage_frais_gestion', models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage des dons consacré aux frais de gestion', max_digits=5)),
                ('rapport_annuel', models.FileField(blank=True, null=True, upload_to='associations/rapports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('comptes_annuels', models.FileField(blank=True, null=True, upload_to='associations/comptes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('transparent_finances', models.BooleanField(default=False)),
                ('transparent_actions', models.BooleanField(default=False)),
                ('projets_phares', models.TextField(blank=True, help_text='Projets principaux réalisés', null=True)),
                ('actions_en_cours', models.TextField(blank=True, null=True)),
                ('partenariats', models.TextField(blank=True, null=True)),
                ('audit_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_creation_profile', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('valide', models.BooleanField(default=False, help_text="Profil validé par l'administration")),
                ('featured', models.BooleanField(default=False, help_text='Mise en avant sur la plateforme')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'association'}, on_delete=django.db.models.deletion.CASCADE, related_name='association_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
                'ordering': ['-featured', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='AssociationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='associations/galerie/')),
                ('legende', models.CharField(blank=True, max_length=200, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.association')),
            ],
            options={
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
        migrations.AddField(
            model_name='association',
            name='images_galerie',
            field=models.ManyToManyField(blank=True, related_name='associations', to='core.associationimage'),
        ),
        migrations.AddIndex(
            model_name='association',
            index=models.Index(fields=['nom'], name='core_associ_nom_f4651f_idx'),
        ),
        migrations.AddIndex(
            model_name='association',
            index=models.Index(fields=['domaine_principal'], name='core_associ_domaine_1aaa1d_idx'),
        ),
        migrations.AddIndex(
            model_name='association',
            index=models.Index(fields=['ville'], name='core_associ_ville_9c5d19_idx'),
        ),
        migrations.AddIndex(
            model_name='association',
            index=models.Index(fields=['valide'], name='core_associ_valide_e4e203_idx'),
        ),
        migrations.AddIndex(
            model_name='association',
            index=models.Index(fields=['featured'], name='core_associ_feature_b9f9de_idx'),
        ),
    ]
