# Generated by Django 5.2.6 on 2025-09-13 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_association_associationimage_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='association',
            name='core_associ_nom_f4651f_idx',
        ),
        migrations.RemoveIndex(
            model_name='association',
            name='core_associ_domaine_1aaa1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='association',
            name='core_associ_ville_9c5d19_idx',
        ),
        migrations.RemoveIndex(
            model_name='association',
            name='core_associ_valide_e4e203_idx',
        ),
        migrations.RemoveIndex(
            model_name='association',
            name='core_associ_feature_b9f9de_idx',
        ),
        migrations.RemoveField(
            model_name='association',
            name='date_publication_journal_officiel',
        ),
        migrations.RemoveField(
            model_name='association',
            name='numero_rna',
        ),
        migrations.AddField(
            model_name='association',
            name='agrement_file',
            field=models.FileField(blank=True, null=True, upload_to='associations/agrements/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name="Copie de l'agrément"),
        ),
        migrations.AddField(
            model_name='association',
            name='commune',
            field=models.CharField(blank=True, help_text="Commune d'implantation", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='date_agrement',
            field=models.DateField(blank=True, help_text="Date d'obtention de l'agrément", null=True, verbose_name="Date d'agrément"),
        ),
        migrations.AddField(
            model_name='association',
            name='numero_agrement',
            field=models.CharField(blank=True, help_text="Numéro d'agrément délivré par le gouvernement malien", max_length=50, null=True, verbose_name="Numéro d'agrément"),
        ),
        migrations.AddField(
            model_name='association',
            name='numero_ifu',
            field=models.CharField(blank=True, help_text='Identifiant Fiscal Unique', max_length=50, null=True, verbose_name='Numéro IFU/Numéro contribuable'),
        ),
        migrations.AddField(
            model_name='association',
            name='numero_rc',
            field=models.CharField(blank=True, help_text="Numéro d'immatriculation au RCCM", max_length=50, null=True, verbose_name='Numéro au Registre du Commerce'),
        ),
        migrations.AddField(
            model_name='association',
            name='statuts_file',
            field=models.FileField(blank=True, null=True, upload_to='associations/statuts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Copie des statuts'),
        ),
        migrations.AlterField(
            model_name='association',
            name='adresse_siege',
            field=models.TextField(verbose_name='Adresse du siège social'),
        ),
        migrations.AlterField(
            model_name='association',
            name='budget_annuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Budget annuel (FCFA)'),
        ),
        migrations.AlterField(
            model_name='association',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='date_creation',
            field=models.DateField(verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='association',
            name='nombre_adherents',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'adhérents"),
        ),
        migrations.AlterField(
            model_name='association',
            name='nombre_beneficiaires',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de bénéficiaires'),
        ),
        migrations.AlterField(
            model_name='association',
            name='pays',
            field=models.CharField(default='Mali', max_length=100),
        ),
        migrations.AlterField(
            model_name='association',
            name='pourcentage_frais_gestion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage des ressources consacré aux frais de fonctionnement (hors missions).\n        <br>• < 15% : Excellent\n        <br>• 15-25% : Bon\n        <br>• 25-35% : Acceptable\n        <br>• > 35% : Élevé', max_digits=5, verbose_name='Frais de gestion (%)'),
        ),
        migrations.AlterField(
            model_name='association',
            name='statut_juridique',
            field=models.CharField(choices=[('agreement', 'Accord de Siège (Organisations Internationales)'), ('ong', 'ONG Internationale'), ('association', 'Association Malienne'), ('fondation', 'Fondation'), ('giec', "GIEC (Groupement d'Intérêt Économique et Culturel)"), ('cooperative', 'Coopérative'), ('autre', 'Autre statut')], default='association', max_length=20),
        ),
        migrations.AlterField(
            model_name='association',
            name='transparent_actions',
            field=models.BooleanField(default=False, verbose_name='Transparence des actions'),
        ),
        migrations.AlterField(
            model_name='association',
            name='transparent_finances',
            field=models.BooleanField(default=False, verbose_name='Transparence financière'),
        ),
        migrations.AlterField(
            model_name='association',
            name='ville',
            field=models.CharField(default='Bamako', max_length=100),
        ),
    ]
