# Generated by Django 5.2.6 on 2025-09-14 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_association_domaines_secondaires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_creation_profile',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('porteur', 'Porteur de Projet'), ('donateur', 'Donateur/Philanthrope'), ('investisseur', 'Investisseur'), ('association', 'Association/ONG')], default='porteur', max_length=15),
        ),
    ]
