# Generated by Django 5.2.6 on 2025-09-13 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_association_core_associ_nom_f4651f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_donateu_ddc028_idx',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='donateur_anonymise',
            new_name='contributeur_anonymise',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='donateur',
        ),
        migrations.AddField(
            model_name='transaction',
            name='contributeur',
            field=models.ForeignKey(default='', limit_choices_to={'user_type__in': ['porteur', 'donateur', 'investisseur', 'association']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='montant_hbar',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='taux_conversion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hedera_account_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hedera_public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['contributeur'], name='core_transa_contrib_b08259_idx'),
        ),
    ]
