# Generated by Django 5.2.6 on 2025-09-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_date_creation_profile_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
