# Generated by Django 5.2.6 on 2025-09-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_association_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='titre',
            field=models.CharField(max_length=250),
        ),
    ]
