# Generated by Django 5.2.6 on 2025-09-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_projet_slug_alter_projet_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='wallet_configure',
            field=models.BooleanField(default=False, help_text='Indique si le wallet est configuré pour les transactions'),
        ),
    ]
