# Generated by Django 5.2.6 on 2025-09-14 23:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_projet_wallet_configure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_soumission', models.DateTimeField(default=django.utils.timezone.now)),
                ('traite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Soumission de contact',
                'verbose_name_plural': 'Soumissions de contact',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.EmailField(max_length=254, verbose_name='Destinataire')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('corps', models.TextField(verbose_name='Corps du message')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('statut', models.CharField(choices=[('sent', 'Envoyé'), ('failed', 'Échec'), ('simulated', 'Simulé'), ('pending', 'En attente')], default='pending', max_length=10, verbose_name='Statut')),
                ('type_email', models.CharField(choices=[('project_approved', 'Projet approuvé'), ('project_rejected', 'Projet rejeté'), ('don_received', 'Don reçu'), ('user_welcome', 'Bienvenue utilisateur'), ('password_reset', 'Réinitialisation mot de passe'), ('notification', 'Notification'), ('other', 'Autre')], default='other', max_length=20, verbose_name="Type d'email")),
                ('erreur', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur concerné')),
            ],
            options={
                'verbose_name': "Log d'email",
                'verbose_name_plural': "Logs d'emails",
                'ordering': ['-date_creation'],
            },
        ),
    ]
