# Generated by Django 5.2.6 on 2025-09-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactsubmission_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='identifiant_unique',
            field=models.CharField(blank=True, help_text='Identifiant unique du projet, généré automatiquement', max_length=20, null=True, unique=True),
        ),
    ]
