# Generated by Django 5.2.6 on 2025-09-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_projet_identifiant_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hedera_private_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
