# Generated by Django 5.2.6 on 2025-09-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_hedera_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='hedera_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='hedera_private_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
