# Generated by Django 5.2.6 on 2025-09-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_projet_hedera_account_id_projet_hedera_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hedera_public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
