# Generated by Django 5.2.6 on 2025-09-17 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_hedera_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCSProjectTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100, unique=True)),
                ('topic_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('memo', models.TextField(blank=True)),
                ('admin_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic HCS Projet',
                'verbose_name_plural': 'Topics HCS Projets',
            },
        ),
        migrations.CreateModel(
            name='HCSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.BigIntegerField()),
                ('consensus_timestamp', models.DateTimeField()),
                ('message_type', models.CharField(choices=[('PROJECT_VALIDATION', 'Validation de projet'), ('TRANSACTION_ATTEMPT', 'Tentative de transaction'), ('TRANSACTION_RESULT', 'Résultat de transaction'), ('OTHER', 'Autre')], max_length=50)),
                ('content', models.JSONField()),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.hcsprojecttopic')),
            ],
            options={
                'verbose_name': 'Message HCS',
                'verbose_name_plural': 'Messages HCS',
                'ordering': ['-consensus_timestamp'],
            },
        ),
    ]
