# Generated by Django 5.2.6 on 2025-09-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_hcsprojecttopic_hcsmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(default=dict),
        ),
    ]
