# Generated by Django 5.2.6 on 2025-09-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_auditlog_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hcsprojecttopic',
            name='admin_creator',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='HCSMessage',
        ),
        migrations.DeleteModel(
            name='HCSProjectTopic',
        ),
    ]
