# Generated by Django 5.2.6 on 2025-09-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_hcsprojecttopic_admin_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='topic_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
