# Generated by Django 5.2.6 on 2025-09-19 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_projet_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='hedera_topic_created',
            field=models.BooleanField(default=False, help_text='Indique si le topic HCS a été créé sur Hedera'),
        ),
        migrations.AddField(
            model_name='projet',
            name='hedera_topic_hashscan_url',
            field=models.URLField(blank=True, help_text='URL HashScan pour le topic HCS', null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='hedera_topic_transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID de création du topic HCS', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hedera_hashscan_url',
            field=models.URLField(blank=True, help_text='URL HashScan pour visualiser la transaction', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hedera_message_hashscan_url',
            field=models.URLField(blank=True, help_text='URL HashScan pour le message HCS', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hedera_message_id',
            field=models.CharField(blank=True, help_text='ID du message HCS envoyé pour cette transaction', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hedera_status',
            field=models.CharField(blank=True, help_text='Statut Hedera de la transaction (SUCCESS, FAILED, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Topic HCS du projet associé à cette transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_by_topic', to='core.projet', to_field='topic_id'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['topic'], name='core_transa_topic_i_e48799_idx'),
        ),
    ]
