# Generated by Django 5.2.6 on 2025-09-19 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_projet_hedera_topic_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='montant_hbar',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
