# Generated by Django 5.2.6 on 2025-09-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_transaction_montant_hbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='montant_hbar',
        ),
    ]
