# Generated by Django 5.2.6 on 2025-09-22 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_transaction_montant_hbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage de commission retenue par la plateforme avant distribution au porteur', max_digits=5),
        ),
        migrations.CreateModel(
            name='Palier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=15)),
                ('montant_minimum', models.DecimalField(decimal_places=0, editable=False, max_digits=15)),
                ('transfere', models.BooleanField(default=False)),
                ('date_transfert', models.DateTimeField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=100)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers', to='core.projet')),
            ],
            options={
                'ordering': ['montant_minimum'],
            },
        ),
        migrations.CreateModel(
            name='TransactionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_brut', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission_pourcentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transaction_hash', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type_transaction', models.CharField(choices=[('distribution', 'Distribution'), ('commission', 'Commission')], max_length=20)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projet')),
            ],
        ),
    ]
