# Generated by Django 5.2.6 on 2025-09-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_projet_commission_palier_transactionadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='montant_distribue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='projet',
            name='montant_engage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination',
            field=models.CharField(choices=[('operator', 'Vers opérateur'), ('project', 'Vers projet direct'), ('beneficiary', 'Vers bénéficiaire')], default='operator', max_length=20),
        ),
    ]
