# Generated by Django 5.2.6 on 2025-09-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_projet_montant_distribue_projet_montant_engage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Pourcentage de commission retenue par la plateforme avant distribution au porteur', max_digits=5),
        ),
    ]
