# Generated by Django 5.2.6 on 2025-09-22 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_auditlog_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreuvePalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('non_soumis', 'Non soumis'), ('en_attente', 'En attente de vérification'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('modification', 'Modification requise')], default='non_soumis', max_length=20)),
                ('commentaires', models.TextField(blank=True)),
                ('palier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves', to='core.palier')),
                ('verificateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preuves_verifiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preuve de palier',
                'verbose_name_plural': 'Preuves de paliers',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='FichierPreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='preuves/%Y/%m/%d/')),
                ('type_fichier', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo'), ('document', 'Document'), ('autre', 'Autre')], max_length=20)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('preuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='core.preuvepalier')),
            ],
            options={
                'verbose_name': 'Fichier preuve',
                'verbose_name_plural': 'Fichiers preuves',
            },
        ),
    ]
