# Generated by Django 5.2.6 on 2025-09-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_preuvepalier_fichierpreuve'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hcs_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
