# Generated by Django 5.2.6 on 2025-09-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_transaction_hcs_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='hcs_message_id',
        ),
    ]
