# Generated by Django 5.2.6 on 2025-09-22 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_transaction_hcs_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_message', models.CharField(max_length=100)),
                ('utilisateur_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('contenu', models.JSONField(default=dict)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.projet')),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
    ]
